#!/bin/bash

# DiabScan Pro - Quick Start Script
# Copy and paste these commands one at a time into your terminal

echo "================================"
echo "DiabScan Pro - Quick Start Guide"
echo "================================"
echo ""

echo "STEP 1: Navigate to project folder"
echo "$ cd /path/to/diabscan-pro"
echo ""
echo "For example:"
echo "  Windows: cd C:\\Users\\YourName\\Desktop\\diabscan-pro"
echo "  Mac:     cd ~/Desktop/diabscan-pro"
echo ""

echo "STEP 2: Verify Node.js is installed"
echo "$ node --version"
echo "(Should show v20.x or higher)"
echo ""

echo "STEP 3: Install pnpm (if you don't have it)"
echo "$ npm install -g pnpm"
echo ""

echo "STEP 4: Install all project dependencies"
echo "$ pnpm install"
echo "(Wait 1-3 minutes for packages to download)"
echo ""

echo "STEP 5: Start the development server"
echo "$ pnpm dev"
echo ""

echo "STEP 6: Open your browser"
echo "Visit: http://localhost:3000"
echo ""

echo "================================"
echo "YOUR APP IS NOW RUNNING!"
echo "================================"
echo ""

echo "NEXT STEPS:"
echo ""
echo "1. You should see the professional auth landing page"
echo ""
echo "2. Click 'Create New Account' and register with:"
echo "   Email: test@example.com"
echo "   Password: TestPassword123!"
echo ""
echo "3. Follow the 4-step process:"
echo "   - Fingerprint Scan (or upload image)"
echo "   - Enter Health Metrics"
echo "   - Get Prediction Results"
echo ""

echo "4. Test on mobile (same Wi-Fi):"
echo "   Find your computer IP:"
echo "     Windows: Run 'ipconfig', find IPv4 Address (e.g., 192.168.1.5)"
echo "     Mac: Run 'ipconfig getifaddr en0'"
echo "   On phone browser: http://192.168.1.5:3000"
echo ""

echo "================================"
echo "DEPLOYMENT (Make it live)"
echo "================================"
echo ""

echo "OPTION 1: One-click in v0.app"
echo "- Click 'Publish' button in v0"
echo "- Wait 2-3 minutes"
echo "- Get live URL"
echo ""

echo "OPTION 2: Deploy with Vercel CLI"
echo ""
echo "$ npm install -g vercel"
echo "$ vercel login"
echo "$ vercel"
echo ""
echo "(Answer the prompts, press Enter for defaults)"
echo ""

echo "OPTION 3: Deploy via GitHub"
echo ""
echo "$ git init"
echo "$ git add ."
echo "$ git commit -m 'DiabScan Pro v1.0'"
echo "$ git branch -M main"
echo "$ git remote add origin https://github.com/YOUR_USERNAME/diabscan-pro.git"
echo "$ git push -u origin main"
echo ""
echo "Then at vercel.com/new, import your GitHub repo"
echo ""

echo "================================"
echo "USEFUL COMMANDS"
echo "================================"
echo ""
echo "pnpm dev       - Start development server"
echo "pnpm build     - Build production version"
echo "pnpm start     - Run production build"
echo "Ctrl + C       - Stop the server"
echo "vercel         - Deploy to internet"
echo ""

echo "================================"
echo "NEED HELP?"
echo "================================"
echo ""
echo "Read these files in your project:"
echo "  - INSTALLATION_GUIDE.md (detailed setup)"
echo "  - PROJECT_SUMMARY.md (full project overview)"
echo "  - README.md (quick overview)"
echo ""
echo "Check browser console for errors: Ctrl + Shift + I (or Cmd + Option + I on Mac)"
echo ""

echo "================================"
echo "TROUBLESHOOTING"
echo "================================"
echo ""
echo "If 'pnpm: command not found'"
echo "  Run: npm install -g pnpm"
echo ""
echo "If 'Port 3000 already in use'"
echo "  Run: pnpm dev -p 3001"
echo ""
echo "If packages not installing"
echo "  Run: pnpm install --force"
echo ""
echo "If changes not showing"
echo "  Hard refresh: Ctrl + Shift + R (Cmd + Shift + R on Mac)"
echo ""
